[[models]]
# モデル名
name = "ai4_1024"
# ビルボーディング表示設定
billboarding = false
# AR 空間上のモデルの拡大率
<<<<<<< HEAD
scale = 30
=======
scale = 7
>>>>>>> 849b8ecf2dad44cd904980642558081133b2c90f
# AR 空間上のモデルの表示位置
[models.position]
x = 0 # 左右位置調整
y = 0 # 上下位置調整
z = 0 # 前後位置調整
# AR 空間上のモデルの表示角度調整
[models.rotation]
x = 0
y = 0
z = 0
# モデルの当たり判定とモーショングループの紐付け
[models.hitInfo]
# 当たり判定ID = "モーショングループ名"
HitArea_body = "YAWN"
